KS-2-1 average mark v2
goolander/KotlinSprints pull request #12
Opened 2024-10-22 21:28 UTC by goolander

2024-10-23 20:51 UTC, ievetrovdev requested changes

2024-10-23 20:51 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task1.kt
Удали этот файл, он тут не нужен

2024-10-24 20:39 UTC, goolander commented on src/main/kotlin/lesson_2/lesson2_task1.kt
Правильно удалил?

2024-10-24 22:07 UTC, ievetrovdev requested changes

2024-10-24 22:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task1.kt
Нет, он все еще есть. Нужно сделать так:
- переключиться в ветку текущего ПР
- удалить лишний файл с задачей (физически из проекта)
- сделать коммит (с изменением удаления)
- прислать ссылку на этот же пулл реквест снова в бот

2024-10-27 21:49 UTC, ievetrovdev approved these changes
Отлично, все верно! Осторожнее добавляй файлы в коммиты

2024-10-27 22:31 UTC, merged